# Generated by Django 6.0.3 on 2026-05-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_evaluations', '0002_alter_academicevaluation_submitted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicevaluation',
            options={'ordering': ['-created_at'], 'permissions': [('can_submit_academic_evaluation', 'Can submit academic evaluation'), ('can_view_academic_evaluation', 'Can view their own academic evaluation'), ('can_edit_academic_evaluation', 'Can edit academic evaluation')]},
        ),
    ]
