# Generated by Django 6.0.3 on 2026-05-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_evaluations', '0003_alter_academicevaluation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicevaluation',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
