# Generated by Django 6.0.3 on 2026-03-27 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internship_placement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightedScoreComputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('communication_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('professionalism_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('F', 'F')], max_length=2)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighted_scores', to='internship_placement.internshipplacement')),
            ],
        ),
    ]
