# Generated by Django 6.0.3 on 2026-05-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipplacement',
            name='placement_letter',
            field=models.FileField(blank=True, null=True, upload_to='placement_documents/'),
        ),
    ]
