# Generated by Django 6.0.3 on 2026-05-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_initial'),
    ]

    operations = [
    ]
