# Generated by Django 6.0.3 on 2026-05-05 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='internshipplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student', 'status'), name='unique_active_placement_per_student'),
        ),
    ]
