# Generated by Django 6.0.3 on 2026-05-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_internshipplacement_unique_active_placement_per_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipplacement',
            options={'permissions': [('can_request_placements', 'Can request placements'), ('can_approve_placements', 'Can approve placements'), ('can_manage_placements', 'Can manage placements')]},
        ),
    ]
