# Generated by Django 6.0.3 on 2026-05-08 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_auto'),
    ]

    operations = [
    ]
