# Generated by Django 6.0.3 on 2026-05-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_internshipplacement_placement_letter'),
        ('placements', '0004_alter_internshipplacement_options'),
    ]

    operations = [
    ]
