# Generated by Django 6.0.3 on 2026-05-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
    ]
