<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-05-08 15:58
=======
# Generated by Django 6.0.3 on 2026-05-08 18:00
>>>>>>> 56c9b0c569d04a063419f0474f0325ef792260a2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_customuser_department_customuser_faculty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
