# Generated by Django 6.0.3 on 2026-05-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_customuser_department_customuser_faculty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
