# Generated by Django 6.0.4 on 2026-05-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_customuser_first_name_and_more'),
        ('user_accounts', '0005_delete_passwordresetotp'),
    ]

    operations = [
    ]
