# Generated by Django 6.0.3 on 2026-05-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_remove_customuser_username'),
        ('user_accounts', '0005_delete_passwordresetotp'),
    ]

    operations = [
    ]
