# Generated by Django 6.0.3 on 2026-05-07 20:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('activities', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('lesson', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('deadline', models.DateField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='placements.internshipplacement')),
            ],
            options={
                'ordering': ['-week_number'],
                'permissions': [('can_submit_weekly_log', 'Can submit weekly log'), ('can_review_weekly_log', 'Can review weekly log'), ('can_approve_weekly_log', 'Can approve weekly log')],
                'unique_together': {('placement', 'week_number')},
            },
        ),
    ]
