# Generated by Django 6.0.3 on 2026-05-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklylogbook',
            options={'ordering': ['-week_number'], 'permissions': [('can_submit_weekly_log', 'Can submit weekly log'), ('can_review_weekly_log', 'Can review weekly log'), ('can_approve_weekly_log', 'Can approve weekly log'), ('can_reject_weekly_log', 'Can reject weekly log')]},
        ),
        migrations.AlterField(
            model_name='weeklylogbook',
            name='supervisor_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
