# Generated by Django 6.0.3 on 2026-05-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_logs', '0002_alter_weeklylogbook_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylogbook',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='log_attachments/'),
        ),
    ]
