# Generated by Django 6.0.3 on 2026-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_logs', '0004_weeklylogbook_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylogbook',
            name='workplace_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklylogbook',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('workplace_reviewed', 'Workplace Reviewed'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
