# Generated by Django 3.2.25 on 2026-03-10 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from .models import UserProfile
from .Evaluation import AcademicEvaluation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('weight', models.DecimalField(decimal_places=3, help_text='Weight as decimal → 0.400 = 40%', max_digits=4)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Evaluation Criteria',
            },
        ),
        migrations.CreateModel(
            name='InternshipPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_supervisor', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'ACADEMIC_SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_placements', to=settings.AUTH_USER_MODEL, verbose_name='Academic Supervisor')),
                ('student', models.OneToOneField(limit_choices_to={'profile__role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='placement', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('workplace_supervisor', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'WORKPLACE_SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_placements', to=settings.AUTH_USER_MODEL, verbose_name='Workplace Supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('activities', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('learnings', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='books.internshipplacement')),
                ('student', models.ForeignKey(limit_choices_to={'profile__role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_number'],
                'unique_together': {('student', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student Intern'), ('ADMIN', 'Internship Administrator'), ('WORKPLACE_SUPERVISOR', 'Workplace Supervisor'), ('ACADEMIC_SUPERVISOR', 'Academic Supervisor')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comments', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.evaluationcriteria')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='books.weeklylog')),
                ('supervisor', models.ForeignKey(limit_choices_to=models.Q(('profile__role__in', ['WORKPLACE_SUPERVISOR', 'ACADEMIC_SUPERVISOR'])), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criterion__name'],
                'unique_together': {('log', 'criterion', 'supervisor')},
            },
        ),
    ]
